routes/web.php
<?php

use App\Http\Controllers\administrativoController;
use App\Http\Controllers\alumnoController;
use App\Http\Controllers\bitacoraController;
use App\Http\Controllers\apoderadoController;
use App\Http\Controllers\boletinController;
use App\Http\Controllers\cardexController;
use App\Http\Controllers\cursoController;
use App\Http\Controllers\homeController;
use App\Http\Controllers\inscripcionController;
use App\Http\Controllers\materiaController;
use App\Http\Controllers\notasController;
use App\Http\Controllers\pagoMensualidadController;
use App\Http\Controllers\pagoSalarioController;
use App\Http\Controllers\profesorController;
use App\Http\Controllers\registroController;
use App\Http\Controllers\usuarioController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();

Route::get('welcome', function() {
    return view('welcome');
});


Route::get('/', [\App\Http\Controllers\Auth\LoginController::class, 'showLoginForm']);
Route::get('/home', [HomeController::class, 'homePage'])->name('home')->middleware('auth');

//ruta para el home
Route::resource('home', homeController::class);

//ruta para alumno
Route::resource('alumno', alumnoController::class);

//ruta para apoderado
Route::resource('apoderado', apoderadoController::class);

//ruta para profesor
Route::resource('profesor', profesorController::class);

//ruta para administrativo
Route::resource('administrativo', administrativoController::class);

//ruta para usuario
Route::resource('usuario', usuarioController::class);
Route::post('usuario/{id}/reset', [usuarioController::class, 'updateEstado'])->name('reset');

//ruta para materia
Route::resource('materia', materiaController::class);

//ruta para curso
Route::resource('curso', cursoController::class);

//ruta para la inscripcion
Route::resource('inscripcion', inscripcionController::class);

//rutas para pago mensualidad
Route::resource('mensualidad', pagoMensualidadController::class);
Route::get('mensualidad/index/download-PDF', [pagoMensualidadController::class, 'PDFList'])->name('mensualidad.PDFList');


//ruta para cardex
Route::resource('cardex', cardexController::class);


//ruta para bitacora
Route::resource('bitacora', bitacoraController::class)->only(['show','index']);
Route::get('bitacora/{id}/download-PDF', [bitacoraController::class, 'downloadPDF'])->name('bitacora.pdf');


//ruta para pago salario
Route::resource('salario',pagoSalarioController::class);
Route::get('salario/index/dowload-PDF', [pagoSalarioController::class,'PDFList'])->name('salario.PDFList');

//ruta para boletin
Route::get('/boleta/{id}/trim1',[boletinController::class, 'trim1'])->name('boletin.trim1');
Route::get('/boleta/{id}/trim2',[boletinController::class, 'trim2'])->name('boletin.trim2');
Route::get('/boleta/{id}/trim3',[boletinController::class, 'trim3'])->name('boletin.trim3');
Route::get('/reporteTrim1/{id}','App\Http\Controllers\boletinController@reporteTrim1')->name('boletinTrim1');
Route::get('/reporteTrim2/{id}','App\Http\Controllers\boletinController@reporteTrim2')->name('boletinTrim2');
Route::get('/reporteTrim3/{id}','App\Http\Controllers\boletinController@reporteTrim3')->name('boletinTrim3');
Route::resource('boletin',boletinController::class);

//ruta para reportes
Route::get('/reporteMensualidad/{id}', 'App\Http\Controllers\pagoMensualidadController@generarReporte')->name('reporteMensualidad');
Route::get('/reporteSalario/{id}', 'App\Http\Controllers\pagoSalarioController@generarReporte')->name('reporteSalario');



//ruta para las notas
Route::get('/notasMod', [notasController::class, 'mod'])->name('mod.notas');
Route::resource('notas', notasController::class);

app/Models/pagoSalarios.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class pagoSalarios extends Model
{
    use HasFactory;

    public $timestamps = false;

    protected $fillable = [
        'id_pago',
        'nro_pago',
        'id_profesor',
        'descuento_iva',
        'aporte_afp'
    ];
}

app/Http/Controllers/DataBaseControllers/PagoSalariosController.php
<?php

namespace App\Http\Controllers;

use App\Models\pagoSalarios;
use Illuminate\Http\Request;

class PagoSalariosController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\pagoSalarios  $pagoSalarios
     * @return \Illuminate\Http\Response
     */
    public function show(pagoSalarios $pagoSalarios)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\pagoSalarios  $pagoSalarios
     * @return \Illuminate\Http\Response
     */
    public function edit(pagoSalarios $pagoSalarios)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\pagoSalarios  $pagoSalarios
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, pagoSalarios $pagoSalarios)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\pagoSalarios  $pagoSalarios
     * @return \Illuminate\Http\Response
     */
    public function destroy(pagoSalarios $pagoSalarios)
    {
        //
    }
}

app/Http/Controllers/pagoSalarioController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\StorePagoSalario;
use App\Models\pagoSalarios;
use App\Models\pagos;
use App\Models\profesores;
use App\Models\Persona;
use Carbon\Carbon;
use Database\Seeders\PersonaSeeder;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use PDF;

class pagoSalarioController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
        $this->middleware("roles:Director,Secretaria,none");
    }
    public function index() {
        $personas = Persona::join('profesores', 'id_persona', 'personas.id')
        ->join('pago_salarios', 'pago_salarios.id_profesor', 'profesores.id')
        ->join('pagos', 'pagos.id', 'pago_salarios.id_pago')
        ->select('personas.*', 'pago_salarios.id AS idPago', 'pago_salarios.nro_pago', 'pagos.monto')
        ->orderBy('idPago', 'desc')->get();
        return view('PagoSalario.index', compact('personas'))->with('i');
    }

    public function create(Request $request) {
        $id = $request->id != null? trim($request->id):1;
        $profesor = profesores::find($id);
        if($profesor == null){
            $persona = null;
            return view('PagoSalario.create', compact('id', 'profesor', 'persona'));
        }
        $persona = Persona::findOrFail($profesor->id_persona);
        return view('PagoSalario.create', compact('id', 'profesor', 'persona'));
    }

    public function store(StorePagoSalario $request) {
        $pago = pagos::create([
            'monto' => $request->monto,
            'fecha' => Carbon::now()->format('Y,m,d')
        ]);
        $pago->save();
        
        $pagoSalario = pagoSalarios::create([
            'id_pago' => $pago->id,
            'nro_pago' => $request->pago,
            'id_profesor' => $request->id_profesor,
            'descuento_iva' => number_format($request->monto * (12.5 / 100), 2),
            'aporte_afp' => number_format($request->monto * (12.71 / 100), 2)
        ]);
        $pagoSalario->save();
        $id = $pago->id_pago;

        bitacoraController::bitacoraRegister(Auth::user()->id, 'Pago Salario registrado ID: '.$pagoSalario->id);

        return redirect()->route('salario.index')->with(
            'success',
            'Pago registrado correctamente'
        );
    }

    public function show($id) {
        $pagoSalario = pagoSalarios::findOrFail($id);
        $pago = pagos::findOrFail($pagoSalario->id_pago);
        $profesor = profesores::findOrFail($pagoSalario->id_profesor);
        $persona = Persona::findOrFail($profesor->id_persona);
        return view('PagoSalario.show', compact('persona', 'pago', 'profesor', 'pagoSalario'));
    }

    public function generarReporte(Request $request, $id)
    {
        $pagoSalario = pagoSalarios::findOrFail($id);
        $pago = pagos::findOrFail($pagoSalario->id_pago);
        $profesor = profesores::findOrFail($pagoSalario->id_profesor);
        $persona = Persona::findOrFail($profesor->id_persona);
        $data = [
            'pagoSalario' => $pagoSalario,
            'pago' => $pago,
            'profesor' => $profesor,
            'persona' => $persona,
        ];
          
        $pdf = PDF::loadView('PagoSalario.reporte', $data);

        return $pdf->download('reporteSalario.pdf');
    }

    public function PDFList(){
        
        $meses = [
            0 => 'Febrero',
            1 => 'Marzo',
            2 => 'Abril',
            3 => 'Mayo',
            4 => 'Junio',
            5 => 'Julio',
            6 => 'Agosto',
            7 => 'Septiembre',
            8 => 'Octubre',
            9 =>  'Noviembre',
        ];
        $pagos = [];
        for($i = 1; $i<=10; $i++){
            if(pagoSalarioController::existePago($i)){
                $consultaPagos = pagoSalarios::where('nro_pago', '=', $i);

                $pagos[] = Persona::join('profesores','profesores.id_persona', 'personas.id')
                ->leftJoinSub($consultaPagos, 'pagosSalarios', function($join){
                    $join->on('pagosSalarios.id_profesor','=', 'profesores.id');
                })->leftjoin('pagos', 'pagos.id', 'pagosSalarios.id_pago')
               // ->where('pago_salarios.nro_pago', $i)
                ->select('personas.*', 'profesores.profesion as profesion', 'pagos.monto as monto', 'pagos.fecha as fechaPago','pagosSalarios.nro_pago as nro_pago')
                ->orderBy('personas.apellido_pat','asc')->get(); 
            }
        }
        $pagos = collect($pagos);
        $pdf = PDF::loadView('PagoSalario.indexPDF',['pagos' => $pagos, 'meses' => $meses])->setPaper('a4', 'landscape');
        $tittle = 'Salarios'.Date('Y').'.pdf';
        //return $pagos;
       // return $pdf->stream();
        return $pdf->download($tittle);
    }


    static public function existePago($mes){
        $pagoSalario = pagoSalarios::where('nro_pago', $mes)->first();
        return !empty($pagoSalario);
    }
}

resources/views/PagoSalario/create.blade.php
@extends('layouts.home_plantilla')

@section('title', 'Pago de Salario')
@section('css')
    <style>
      
            @media(max-width: 768px){
                section > div.col-10{
             
                    width: 100%;
                }
                section > div.col-10 > .card{
                    margin: 0% !important;
                }

                #search-input{
                    width: 96% !important
                }

            }
       
   
            
    </style>
@endsection
@section('navigation')
<section class="row justify-content-center" id="main">
    <div class="col-10">
        <div class="card shadow m-5">
            <div class="card-header text-center">
                <h5 class="m-2">Pago de Salarios</h5>
            </div>

                <div class="card-body p-4">
                    <div class="row mb-3">
                        <div id ="search-input" class="col-5 m-2">
                            <form method="GET" action="{{route('salario.create')}}">
                                <div class="input-group">
                                    <input type="number" class="form-control" id="nombreInput" name="id" placeholder="ID Profesor" value="">
                                    <button class="btn btn-outline-primary" type="submit" id="buscar">Buscar</button>
                                </div>
                            </form>
                        </div>
                    </div>
                    <div class="row mb-3 justify-content-around">
                        <div class="col m-2">
                            <div class="card">
                                <div class="card-body">
                                    @if ($persona == null)
                                        <div class = "text-center alert alert-danger">
                                        <p>No hay resultados</p>
                                        </div>      
                                     @else
                                    <div class="row justify-content-around">
                                        <div class="col">
                                            <strong class="mt-2">Datos Personales</strong>
                                            <p class="mb-1 "><span class="fw-bold text-secondary">Nombre completo: </span>{{$persona->nombre}} {{$persona->apellido_pat}} {{$persona->apellido_mat}}</p>
                                            <p class="mb-1"><b class="fw-bold  text-secondary">Ci: </b> {{$persona->ci}}</p>
                                            <p class="mb-1"><b class="fw-bold  text-secondary">Sexo: </b> {{$persona->sexo}}</p>
                                            <p class="mb-1"><b class="fw-bold  text-secondary">Fecha Nacimiento: </b> {{$persona->fecha_nac}}</p>
                                        </div>
                                        <div class="col mb-2">
                                            <strong class="mt-2">Datos Personales</strong>
                                            <p class="mb-1 "><span class="fw-bold text-secondary">ID Profesor: </span> {{$profesor->id}}</p>
                                            <p class="mb-1 "><span class="fw-bold text-secondary">Profesion: </span> {{$profesor->profesion}}</p>
                                        </div>
                                    </div>
                                    @endif
                                </div>
                            </div>
                        </div>
                    </div>
                <form method="POST" action="{{route('salario.store')}}" id="form-reg">
                    @csrf
                    <input type="hidden" name="id_profesor" @if($profesor!=null)value="{{$profesor->id}}"@else value ="" @endif>
                    <div class="row m-2 justify-content-around">
                        <div class="col-4 m-2">
                            <label for="pago" class="fw-bold">
                                Nro. Pago: <br>
                                <input class="form-control" type="number" name="pago" id="pago" placeholder="Nro. de pago"
                                oninvalid="setCustomValidity('Por favor inserte solo números.')">
                            </label>
                            {!! $errors->first('pago', '<br><span class="help-block text-danger">*:message</span>') !!}
                        </div>
                        <div class="col-4 m-2">
                            <label for="monto" class="fw-bold">
                                Monto Bruto: <br>
                                <input class="form-control" type="number" name="monto" id="monto" placeholder="Monto Bs."
                                oninvalid="setCustomValidity('Por favor inserte solo números.')">                                
                            </label>
                            {!! $errors->first('monto', '<br><span class="help-block text-danger">*:message</span>') !!}
                        </div>
                    </div>
                    <div class="row m-2 justify-content-around">
                        <div class="col-4 m-2">
                            <label for="iva" class="fw-bold">
                                % Descuento IVA: <br>
                                <input class="form-control" type="number" value="12.5" name="descuento_iva" id="iva" disabled>
                            </label>
                        </div>
                        <div class="col-4 m-2">
                            <label for="afp" class="fw-bold">
                                % Aporte Laboral: <br>
                                <input class="form-control" type="number" value="12.71" name="aporte_afp" id="afp" disabled>
                            </label>
                        </div>
                    </div>
                    <div class="row-2 text-end m-2">
                        <a class="btn btn-danger" href="{{route('salario.index')}}">Cancelar</a>
                        <button type="submit" class="btn btn-primary" form="form-reg" @if($persona == null) disabled @endif>Registrar</button>
                    </div>
                </form>
        </div>
    </div>
</section>

@endsection

resources/views/PagoSalario/index.blade.php
@extends('layouts.home_plantilla')

@section('title', 'Profesor')

@section('css')
    <style>
        @media (max-width: 768px) {
            .col-9.mt-1.card{
                width: 92%;
            }
        }
    </style>
@endsection
@section('navigation')

    <div class="row justify-content-center">
        <div class="col-9 mt-1 card">
            <div class="row justify-content-between mb-2 card-header">
                <div class="col">
                    <h2>Lista de Pagos</h2>
                </div>
               
                <div class="col d-flex justify-content-end align-items-center">
                    <a class="btn btn-sm btn-dark" style = "margin-right: 0.5rem" href="{{ route('salario.PDFList') }}">PDF</a>
                    <a class="btn btn-sm btn-success" href="{{ route('salario.create') }}">Nuevo pago</a>
                </div>
            </div>
            <div class="card-body table-responsive">
                <table class="table table-round-blue">
                    <thead class="table-head">
                        <tr>
                            <th>Nro</th>
                            <th>Nombre completo</th>
                            <th>Nro. Pago</th>
                            <th>Monto</th>
                            <th width="120px">Acciones</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($personas as $persona)
                            <tr>
                                <td class="text-center">{{ ++$i }}</td>
                                <td>{{ $persona->nombre.' '.$persona->apellido_pat.' '.$persona->apellido_mat }}</td>
                                <td class="text-center">{{ $persona->nro_pago }}</td>
                                <td class="text-center">{{ $persona->monto }} Bs.</td>
                                <td>
                                    <a class="btn btn-sm btn-primary" href="{{route('salario.show', $persona->idPago)}}">Ver</a>
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
@endsection

resources/views/PagoSalario/indexPDF.blade.php
<html>
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

       <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
        integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">

  <style>
    .page-break {
        page-break-after: always;
    }

    body {
      font-family: "Times New Roman", serif;
      margin: 1.5cm 1cm 2cm 1cm;
    }
    
    @page {
        margin: 0cm 1cm;
    }
    header { 
      position: fixed;
      left: 0cm;
      top: 0.25cm;
      right: 0cm;
      height: 50px;
      text-align: center;
    }
    header h1{
      margin: 10px 0;
    }
    header h2{
      margin: 0 0 10px 0;
    }
    footer {
      position: fixed;
      left: 0cm;
      bottom: 1cm;
      right: 0cm;
      height: 40px;
      border-bottom: 2px solid #ddd;
    }
    footer .page:after {
      content: counter(page);
    }
    footer table {
      width: 100%;
    }
    footer p {
      text-align: right;
    }
    footer .izq {
      text-align: left;
    }
  </style>

 
<body>
  <header>
    <table style="width: 100%"> 
      <tr>
          <td style = "width: 5%">
            <div >
                <img  src="./img/logocr1.png" width="50" height="50"
                    alt="Logo Colegio Cristo Rey">
            </div>
          </td> 
          <td> 
            <p style = "text-align: left">
              COLEGIO CRISTO REY 
            </p>         
          </td>
          <td> 
            <p style = "text-align: right">
              LISTA DE PAGO DE SALARIOS
            </p>
          </td>
        </tr>
    </table>
  
  </header>


  <footer>
    <table>
      <tr>
        <td>
            <p class="izq">
             Educando para la eternidad
            </p>
        </td>
        <td>
          <p class="page">
            Página
          </p>
        </td>
      </tr>
    </table>
  </footer>
  
  <main>
    <div style= "text-align: center">
    <h1 > Lista de pagos salarios de la gestion {{Date('Y')}} </h1>
    </div>
  
    <br>
 

    @foreach($pagos as $key => $personas)
        <div id="content">
            <h3> Lista de pagos del mes de {{$meses[$key]}} </h3>  
            <table class="table table-bordered table-sm">
                <thead class="thead-dark">
                    <tr style = "text-align: center">
                        <th>Nro</th>
                        <th>Nombre completo</th>
                        <th>CI</th>
                        <th>Profesion</th>
                        <th>Fecha del pago</th>
                        <th>Monto</th>
                    </tr>
                </thead>
                <tbody>
                    {{$i = 0}}
                    @foreach ($personas as $persona)
                        <tr>
                            <td style = "text-align: center">{{ ++$i }}</td>
                            <td >{{$persona->apellido_pat}} {{$persona->apellido_mat}} {{ $persona->nombre}}</td>
                            <td style = "text-align: center">{{ $persona->ci}}</td>
                            <td style = "text-align: center">{{ $persona->profesion}}</td>
                            @if ($persona->fechaPago == null)
                                <td style = "text-align: center; color: #FF0000;">Sin pagar</td>
                                <td style = "text-align: center; color: #FF0000;">Sin pagar</td>
                            @else
                                <td style = "text-align: center">{{ $persona->fechaPago}}</td>
                                <td style = "text-align: center">{{ $persona->monto}}</td>
                            @endif
                        </tr>
                    @endforeach  
                </tbody>
            </table>
        </div>    
        @if ( ($key != count($pagos)-1) && $pagos[$key+1]!= null  )
            <div class="page-break"></div>
        @endif
    @endforeach
  </main>
  

</body>
</html>
{{--  <!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
        integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
</head>

<body>
    <div class="container">
        <div class="row justify-content-center">
            <h1 class="h1">
                Reporte
            </h1>
            <br>
            <br>
            <table class="table mt-5 table-bordered">
                <thead class="thead-dark">
                    <tr>
                        <th scope="border">Informacion</th>
                        <th scope="border">Valor</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($acciones as $accion)
                    <tr>
                        <th class="text-left">{{$accion->fecha}}</th>
                        <td class="text-right">{{$accion->descripcion}}</td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
    <footer class="float-right">
        <small class="text-muted">
            {{Carbon\Carbon::parse(Carbon\Carbon::now())->locale('es_ES')->isoFormat('LLLL')}}
        </small>
    </footer>
</body>

</html>  --}}

resources/views/PagoSalario/reporte.blade.php
<!DOCTYPE html>
<html>

<head>
    <title>Reporte Pago Salario</title>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
        integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">

    <style>
    .page-break {
        page-break-after: always;
    }

    body {
        font-family: "Times New Roman", serif;
        margin: 2.5cm 1cm 2cm 1cm;
    }

    @page {
        margin: 0cm 1cm;
    }

    header {
        position: fixed;
        left: 0cm;
        top: 0.25cm;
        right: 0cm;
        height: 50px;
        text-align: center;
    }

    header h1 {
        margin: 0 0 10px 0;
    }

    header h2 {
        margin: 0 0 10px 0;
    }

    footer {
        position: fixed;
        left: 0cm;
        bottom: 1cm;
        right: 0cm;
        height: 40px;
        border-bottom: 2px solid #ddd;
    }

    footer .page:after {
        content: counter(page);
    }

    footer table {
        width: 100%;
    }

    footer p {
        text-align: right;
    }

    footer .izq {
        text-align: left;
    }

    th {
        text-align: center
    }
    </style>
</head>

<body>
    <header>
        <table style="width: 100%">
            <tr>
                <td style="width: 8%">
                    <div>
                        <img src="./img/logocr1.png" width="120" height="120"
                            alt="Logo Colegio Cristo Rey">
                    </div>
                </td>
                <td>
                    <p style="text-align: left">
                        COLEGIO CRISTO REY
                    </p>
                </td>
                <td>
                    <p style="text-align: right">
                        EDUCANDO PARA LA ETERNIDAD
                    </p>
                </td>
            </tr>
        </table>
    </header>

    <main>
        <br>
        <br>
        <div style="text-align: center">
            <h2> RECIBO DE PAGO DE SALARIO </h2>
        </div>

        <table class="table table-bordered table-sm ">
            <tr>
                <th colspan="2"><b>Datos Profesor</b></th>
            </tr>
            <tr>
                <td><b>Nombre</b></td>
                <td>{{ $persona->nombre . ' ' . $persona->apellido_pat . ' ' . $persona->apellido_mat }}</td>
            </tr>
            <tr>
                <td><b>CI</b></td>
                <td>{{ $persona->ci }}</td>
            </tr>
            <tr>
                <th colspan="2"><b>Acerca del Pago</b></th>
            </tr>
            <tr>
                <td><b>Nro Cuota</b></td>
                <td>{{ $pagoSalario->nro_pago }}</td>
            </tr>
            <tr>
                <td><b>Monto bruto</b></td>
                <td>Bs. {{ $pago->monto }}</td>
            </tr>
            <tr>
                <td><b>Descuento IVA</b></td>
                <td>Bs. {{$pagoSalario->descuento_iva}}</td>
            </tr>
            <tr>
                <td><b>Aporte AFP</b></td>
                <td>Bs. {{$pagoSalario->aporte_afp}}</td>
            </tr>
            <tr>
                <td><b>Monto neto</b></td>
                <td>Bs. {{$pago->monto - $pagoSalario->descuento_iva - $pagoSalario->aporte_afp}} Bs.</td>
            </tr>
        </table>

    </main>

</body>

</html>