routes/web.php
<?php

use App\Http\Controllers\administrativoController;
use App\Http\Controllers\alumnoController;
use App\Http\Controllers\bitacoraController;
use App\Http\Controllers\apoderadoController;
use App\Http\Controllers\boletinController;
use App\Http\Controllers\cardexController;
use App\Http\Controllers\cursoController;
use App\Http\Controllers\homeController;
use App\Http\Controllers\inscripcionController;
use App\Http\Controllers\materiaController;
use App\Http\Controllers\notasController;
use App\Http\Controllers\pagoMensualidadController;
use App\Http\Controllers\pagoSalarioController;
use App\Http\Controllers\profesorController;
use App\Http\Controllers\registroController;
use App\Http\Controllers\usuarioController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();

Route::get('welcome', function() {
    return view('welcome');
});


Route::get('/', [\App\Http\Controllers\Auth\LoginController::class, 'showLoginForm']);
Route::get('/home', [HomeController::class, 'homePage'])->name('home')->middleware('auth');

//ruta para el home
Route::resource('home', homeController::class);

//ruta para alumno
Route::resource('alumno', alumnoController::class);

//ruta para apoderado
Route::resource('apoderado', apoderadoController::class);

//ruta para profesor
Route::resource('profesor', profesorController::class);

//ruta para administrativo
Route::resource('administrativo', administrativoController::class);

//ruta para usuario
Route::resource('usuario', usuarioController::class);
Route::post('usuario/{id}/reset', [usuarioController::class, 'updateEstado'])->name('reset');

//ruta para materia
Route::resource('materia', materiaController::class);

//ruta para curso
Route::resource('curso', cursoController::class);

//ruta para la inscripcion
Route::resource('inscripcion', inscripcionController::class);

//rutas para pago mensualidad
Route::resource('mensualidad', pagoMensualidadController::class);
Route::get('mensualidad/index/download-PDF', [pagoMensualidadController::class, 'PDFList'])->name('mensualidad.PDFList');


//ruta para cardex
Route::resource('cardex', cardexController::class);


//ruta para bitacora
Route::resource('bitacora', bitacoraController::class)->only(['show','index']);
Route::get('bitacora/{id}/download-PDF', [bitacoraController::class, 'downloadPDF'])->name('bitacora.pdf');


//ruta para pago salario
Route::resource('salario',pagoSalarioController::class);
Route::get('salario/index/dowload-PDF', [pagoSalarioController::class,'PDFList'])->name('salario.PDFList');

//ruta para boletin
Route::get('/boleta/{id}/trim1',[boletinController::class, 'trim1'])->name('boletin.trim1');
Route::get('/boleta/{id}/trim2',[boletinController::class, 'trim2'])->name('boletin.trim2');
Route::get('/boleta/{id}/trim3',[boletinController::class, 'trim3'])->name('boletin.trim3');
Route::get('/reporteTrim1/{id}','App\Http\Controllers\boletinController@reporteTrim1')->name('boletinTrim1');
Route::get('/reporteTrim2/{id}','App\Http\Controllers\boletinController@reporteTrim2')->name('boletinTrim2');
Route::get('/reporteTrim3/{id}','App\Http\Controllers\boletinController@reporteTrim3')->name('boletinTrim3');
Route::resource('boletin',boletinController::class);

//ruta para reportes
Route::get('/reporteMensualidad/{id}', 'App\Http\Controllers\pagoMensualidadController@generarReporte')->name('reporteMensualidad');
Route::get('/reporteSalario/{id}', 'App\Http\Controllers\pagoSalarioController@generarReporte')->name('reporteSalario');



//ruta para las notas
Route::get('/notasMod', [notasController::class, 'mod'])->name('mod.notas');
Route::resource('notas', notasController::class);

app/Models/cursos.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class cursos extends Model
{
    use HasFactory;

    protected $table = 'cursos';
    
    const CREATED_AT = null;
    const UPDATED_AT = null;

    protected $fillable = [
        'nivel',
        'cupo_max',
        'cant_alumnos',
    ];



    public function cant_alumnos($gestion){

        $cant = alumnos::join('inscripciones', 'inscripciones.id_alumno','alumnos.id')
            ->where('inscripciones.id_curso','=', $this->id)
            ->whereYear('inscripciones.fecha', '=', $gestion)
        ->count();

        return $cant;
    }
}

app/Http/Controllers/DataBaseControllers/CursosController.php
<?php

namespace App\Http\Controllers;

use App\Models\cursos;
use Illuminate\Http\Request;

class CursosController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\cursos  $cursos
     * @return \Illuminate\Http\Response
     */
    public function show(cursos $cursos)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\cursos  $cursos
     * @return \Illuminate\Http\Response
     */
    public function edit(cursos $cursos)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\cursos  $cursos
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, cursos $cursos)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\cursos  $cursos
     * @return \Illuminate\Http\Response
     */
    public function destroy(cursos $cursos)
    {
        //
    }
}

app/Http/Controllers/cursoController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\StoreCurso;
use App\Models\alumnos;
use App\Models\cursos;
use App\Models\Persona;
use Illuminate\Database\Eloquent\Collection;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class cursoController extends Controller
{

    public function __construct()
    {
        $this->middleware('auth');
        $this->middleware("roles:Director,Secretaria,none")->except('index','show');
        $this->middleware("roles:Director,Secretaria,Profesor")->only('index','show'); 
    }
    public function index(Request $request){
        $gestion = $request->gestion;
        $cursoA = cursos::all();

        if($gestion == Date('Y')){
            $cursos = $cursoA;
            return view('Curso.index',compact('cursos','gestion'));
        }

        foreach ($cursoA as $curso){
            $curso->cant_alumnos = $curso->cant_alumnos($gestion); 
        }
        $cursos = $cursoA;

        $cursos = $cursos->filter( function($curso){return $curso->cant_alumnos !=0;
            });

        if(empty($cursos->all())){
            return redirect()->route('curso.index',['gestion' => Date('Y')]);
        }    

        return view('Curso.index', compact('cursos','gestion'));
    }


    public function create(){
        return view('Curso.create');
    }

    public function store(StoreCurso $request){
        $curso = cursos::create([
            'nivel' => $request->nivel,
            'cupo_max' => $request->cupos_max,
            'cant_alumnos' => 0,
        ]); 
        $curso->save();
        
        bitacoraController::bitacoraRegister(Auth::user()->id, 'Curso creado ID: '.$curso->id);

        return redirect()->route('curso.index')->with('success', 'Curso creado correctamente');
    }

    public function show($id){
        $curso = cursos::findOrFail($id);
        $personas = Persona::join('alumnos', 'alumnos.id_persona', 'personas.id')
        ->join('inscripciones', 'inscripciones.id_alumno', 'alumnos.id')
        ->where('inscripciones.id_curso', '=', $curso->id)
        ->get();
        return view('Curso.show', compact('personas', 'id'));
    }

    public function edit($id){
        $curso = cursos::findOrFail($id);
        return view('Curso.edit', compact('curso'));
    }
    
    public function update($id, StoreCurso $request){
        $curso = cursos::findOrFail($id);
        $curso->cupo_max = $request->cupos_max;
        $curso->save();

        bitacoraController::bitacoraRegister(Auth::user()->id, 'Modificacion de curso ID: '.$curso->id);

        return redirect()->route('curso.index',['gestion' => Date('Y')])->with('succes', 'Curso editado correctamente');
    }

    static public function cant_alumnos($id_curso) {
        $curso = cursos::findOrFail($id_curso);
        return $curso->cant_alumnos;
    }

    static public function cupo_max($id_curso) {
        $curso = cursos::findOrFail($id_curso);
        return $curso->cupo_max;
    }
}

resources/views/Curso/create.blade.php
@extends('layouts.home_plantilla')

@section('title', 'Crear curso')
@section('css')
    <style>
        @media(max-width: 1045px){
            .card-body  .row{
                display: flex;
                flex-direction: column;
            }
        }

        @media(max-width: 768px){
            #main > .col-9{
                width: 93% !important;
                padding: 0%;
            }
            .card{
                margin: 0% !important;
            }
        }

    </style>
@endsection
@section('navigation')
<section class="vh-100 row justify-content-center align-items-center" id="main">
    <div class="col-9 "  >

        <div class="card shadow m-4">
            <div class="card-header">
                <h5 class="m-2">Datos del curso
                </h5>
            </div>
            <div class="card-body p-4">
                <form method='POST' action='{{route('curso.store')}}'>
                    @csrf
                    <div class="row mb-3 justify-content-around">
                        <div class="col m-2">
                            <label for="nivel">
                                Nivel<br>
                            </label>
                            <select id = "nivel" name = "nivel" class="form-select" aria-label="Disabled select example">
                                <option selected disabled>Elige el nivel del curso</option>
                                <option value = '1'> 1º </option>    
                                <option value = '2'> 2º </option>    
                                <option value = '3'> 3º </option>    
                                <option value = '4'> 4º </option>    
                                <option value = '5'> 5º </option>    
                                <option value = '6'> 6º </option>    
                            </select>
                        </div>
                        <div class="col m-2">
                            <label for="cupos_max">
                                Cantidad maxima de alumnos:<br>
                            </label>
                            <input class="form-control"  id="cupos_max" type="number" name="cupos_max" value="old('cupos_max')"> 
                            {!! $errors->first('cupos_max', '<span class="text-danger">*:message</span>') !!}
                        </div>
                    </div>
                   
                    <div class="mt-3 text-end me-2">
          
                        <a class="btn btn-danger" href="{{route('curso.index')}}">Cancelar</a>

                        <button type="submit"  class="btn btn-primary">
                            Registrar
                        </button>
                    </div>
                    
                </form>
            </div>
        </div>
    </div>
    
</section>
</div>
@endsection

resources/views/Curso/edit.blade.php
@extends('layouts.home_plantilla')

@section('title', 'Crear curso')
@section('css')
    <style>
        @media(max-width: 1045px){
            .card-body  .row{
                display: flex;
                flex-direction: column;
            }
        }

        @media(max-width: 768px){
            #main > .col-9{
                width: 93% !important;
                padding: 0%;
            }
            .card{
                margin: 0% !important;
            }
        }

    </style>
@endsection
@section('navigation')
<section class="vh-100 row justify-content-center align-items-center" id="main">
    <div class="col-9 "  >

        <div class="card shadow m-4">
            <div class="card-header">
                <h5 class="m-2">Datos del curso
                </h5>
            </div>
            <div class="card-body p-4">
                <form method='POST' action="{{route('curso.update', $curso->id)}}">
                    @csrf
                    @method('PUT')
                    <div class="row mb-3 justify-content-around">
                        <div class="col m-2">
                            <label for="nivel">
                                Nivel<br>
                            </label>
                            <input class="form-control" id="nivel" type="text" name="nivel" value = '{{$curso->nivel}}º' disabled> 
                        </div>
                        <div class="col m-2">
                            <label for="cupos_max">
                                Cantidad maxima de alumnos:<br>
                            </label>
                            <input class="form-control" id="cupos_max" type="number" name="cupos_max" min="10" max="100" value = {{$curso->cupo_max}} required> 
                        </div>
                    </div>
                   
                    <div class="mt-3 text-end me-2">

                        <a class="btn btn-danger" href="{{route('curso.index')}}">Cancelar</a>

                        <button type="submit"  class="btn btn-primary">
                            Editar
                        </button>
                    </div>
                    
                </form>
            </div>
        </div>
    </div>
    
</section>
</div>
@endsection

resources/views/Curso/index.blade.php
@extends('layouts.home_plantilla')

@section('title', 'Cursos')
@section('css')
   <style>
    @media(max-width: 768px){
        
        div > div.col-9{
            width: 92%;
            padding: 0%;
        }
    }
   </style>
@endsection
@section('navigation')

    <div class="row justify-content-center">
        <div class="col-9 mt-1 card">
            <div class="row justify-content-between mb-2 card-header">
                <div class="col">
                    <h2>Cursos de la gestion {{ $gestion }}</h2>
                </div>
                @if (Auth::user()->id_rol == 1 || Auth::user()->id_rol == 2)

                    <div class="col d-flex justify-content-end align-items-center">
                        <a class="btn btn-sm btn-success" href="{{ route('curso.create') }}"> Registrar nuevo</a>
                    </div>

                @endif
            </div>
            <div class="card-body table-responsive">
                <table class="table table-round-blue table-striped">
                    <thead class="table-head">
                        <tr>
                            <th>Curso</th>
                            @if ($gestion === Date('Y'))
                                <th> Cupo maximo </th>
                            @endif
                            <th>Cantidad de alumnos</th>
                            <th width="120px">Acciones</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($cursos as $curso)
                            <tr>
                                <td class="text-center">{{ $curso->nivel }}</td>
                                @if ($gestion === Date('Y'))
                                    <td class="text-center"> {{ $curso->cupo_max }} </td>
                                @endif
                                <td class="text-center">{{ $curso->cant_alumnos }}</td>
                                <td class="text-center">
                                    <a class="btn btn-sm btn-primary" href="{{ route('curso.show', $curso->id) }}">Ver</a>
                                    @if (Auth::user()->id_rol == 1 || Auth::user()->id_rol == 2)
                                        @if ($gestion === Date('Y'))
                                            <a class="btn btn-sm btn-secondary"
                                                href="{{ route('curso.edit', $curso->id) }}">Editar</a>
                                        @endif
                                    @endif
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
            </table>

        </div>
    </div>

    </div>
@endsection

@section('js')
<script>
  
    $(document).ready(function() {
        $('.table-round-blue').DataTable({
            destroy: true,
            paging: false,
            searching: false,
            ordering: false,
            info: false
            responsive: true,
            autoWidth: false
        });
    });
</script>
@endsection

resources/views/Curso/show.blade.php
@extends('layouts.home_plantilla')
@section('css')
    <style>
        @media(max-width: 768px){
            div > div.col-9{
                width: 93%;
                padding: 0%;
            }
        }
    </style>
@endsection
@section('title', 'Alumnos')

@section('navigation')

    <div class="row justify-content-center">
        <div class="col-9 mt-1 card">
            <div class="row justify-content-between mb-2 card-header">
                <div class="col">
                    <h2>Alumnos del curso {{$id}}° de Secundaria</h2>
                </div>
            </div>
            <div class="card-body table-responsive">
                <table class="table table-round-blue">
                    <thead class="table-head">
                        <tr>
                            <th>Nro</th>
                            <th>Nombre</th>
                            <th>Apellidos</th>
                            <th width="120px">Acciones</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php
                            $i=0;
                         ?>
                        @foreach ($personas as $persona)
                            <tr>
                                <td>{{ ++$i }}</td>
                                <td>{{ $persona->nombre }}</td>
                                <td>{{ $persona->apellido_pat }} {{ $persona->apellido_mat }}</td>
                                <td>
                                    <a class="btn btn-sm btn-primary" href="{{ route('alumno.show', $persona->id_alumno) }}">Ver</a>
                                    @if (Auth::user()->id_rol == 1 || Auth::user()->id_rol == 2)
                                    <a class="btn btn-sm btn-secondary"
                                        href="{{ route('alumno.edit', $persona->id_alumno) }}">Editar</a>
                                    @endif
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
@endsection
@section('js')
    <script>
        $(document).ready(function() {
            $('.table-round-blue').DataTable( {
                destroy: true,
                paging:   false,
                ordering: false,
                searching: false,
                info:     false,
                responsive: true,
                autoWidth: false,    
                pagingType: "full_numbers",
                language: {
                    "lengthMenu": 'Mostrar <select class = "custom-select form-select form-select-sm">'+
                        '<option value="10">10</option>'+
                        '<option value="25">25</option>'+
                        '<option value="50">50</option>'+
                        '<option value="-1">Todos</option>'+
                        '</select> registros',
                    "zeroRecords": "No existen resultados",
                    "info": "Mostrando _PAGE_ de _PAGES_",
                    "infoEmpty": "No hay resultados",
                    "infoFiltered": "(filtrado de _MAX_ total registros totales)",
                    "search": "Buscar:",
                    "paginate": {
                        "first":      "Primero",
                        "last":       "Último",
                        "next":       "Siguiente",
                        "previous":   "Anterior"
                    },
                }
            } );
        } );
    </script>
@endsection