routes/web.php
<?php

use App\Http\Controllers\administrativoController;
use App\Http\Controllers\alumnoController;
use App\Http\Controllers\bitacoraController;
use App\Http\Controllers\apoderadoController;
use App\Http\Controllers\boletinController;
use App\Http\Controllers\cardexController;
use App\Http\Controllers\cursoController;
use App\Http\Controllers\homeController;
use App\Http\Controllers\inscripcionController;
use App\Http\Controllers\materiaController;
use App\Http\Controllers\notasController;
use App\Http\Controllers\pagoMensualidadController;
use App\Http\Controllers\pagoSalarioController;
use App\Http\Controllers\profesorController;
use App\Http\Controllers\registroController;
use App\Http\Controllers\usuarioController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();

Route::get('welcome', function() {
    return view('welcome');
});


Route::get('/', [\App\Http\Controllers\Auth\LoginController::class, 'showLoginForm']);
Route::get('/home', [HomeController::class, 'homePage'])->name('home')->middleware('auth');

//ruta para el home
Route::resource('home', homeController::class);

//ruta para alumno
Route::resource('alumno', alumnoController::class);

//ruta para apoderado
Route::resource('apoderado', apoderadoController::class);

//ruta para profesor
Route::resource('profesor', profesorController::class);

//ruta para administrativo
Route::resource('administrativo', administrativoController::class);

//ruta para usuario
Route::resource('usuario', usuarioController::class);
Route::post('usuario/{id}/reset', [usuarioController::class, 'updateEstado'])->name('reset');

//ruta para materia
Route::resource('materia', materiaController::class);

//ruta para curso
Route::resource('curso', cursoController::class);

//ruta para la inscripcion
Route::resource('inscripcion', inscripcionController::class);

//rutas para pago mensualidad
Route::resource('mensualidad', pagoMensualidadController::class);
Route::get('mensualidad/index/download-PDF', [pagoMensualidadController::class, 'PDFList'])->name('mensualidad.PDFList');


//ruta para cardex
Route::resource('cardex', cardexController::class);


//ruta para bitacora
Route::resource('bitacora', bitacoraController::class)->only(['show','index']);
Route::get('bitacora/{id}/download-PDF', [bitacoraController::class, 'downloadPDF'])->name('bitacora.pdf');


//ruta para pago salario
Route::resource('salario',pagoSalarioController::class);
Route::get('salario/index/dowload-PDF', [pagoSalarioController::class,'PDFList'])->name('salario.PDFList');

//ruta para boletin
Route::get('/boleta/{id}/trim1',[boletinController::class, 'trim1'])->name('boletin.trim1');
Route::get('/boleta/{id}/trim2',[boletinController::class, 'trim2'])->name('boletin.trim2');
Route::get('/boleta/{id}/trim3',[boletinController::class, 'trim3'])->name('boletin.trim3');
Route::get('/reporteTrim1/{id}','App\Http\Controllers\boletinController@reporteTrim1')->name('boletinTrim1');
Route::get('/reporteTrim2/{id}','App\Http\Controllers\boletinController@reporteTrim2')->name('boletinTrim2');
Route::get('/reporteTrim3/{id}','App\Http\Controllers\boletinController@reporteTrim3')->name('boletinTrim3');
Route::resource('boletin',boletinController::class);

//ruta para reportes
Route::get('/reporteMensualidad/{id}', 'App\Http\Controllers\pagoMensualidadController@generarReporte')->name('reporteMensualidad');
Route::get('/reporteSalario/{id}', 'App\Http\Controllers\pagoSalarioController@generarReporte')->name('reporteSalario');



//ruta para las notas
Route::get('/notasMod', [notasController::class, 'mod'])->name('mod.notas');
Route::resource('notas', notasController::class);

app/Http/Controllers/apoderadoController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\StoreApoderado;
use App\Models\Persona;
use App\Models\tutores;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class apoderadoController extends Controller
{

    public function __construct()
    {
        $this->middleware('auth');
        $this->middleware("roles:Director,Secretaria,none")->except('index','show');
        $this->middleware("roles:Director,Secretaria,Profesor")->only('index','show'); 
    }

    public function index()
    {
        $personas = Persona::join('tutores', 'personas.id', 'tutores.id_persona')
            ->select('tutores.id as idTutor', 'personas.nombre', 'personas.apellido_pat', 'personas.apellido_mat')
            ->orderBy('idTutor', 'desc')->get();
        return view('Apoderado.index', compact('personas'))->with('i');
    }

    public function show($tutorId)
    {

        $tutor = tutores::findOrFail($tutorId);

        if ($tutor == null)
            return redirect()->route('apoderado.index')->with('error', 'No se encontraron los datos del apoderado');

        $persona = Persona::join('tutores', 'tutores.id_persona', 'personas.id')
        ->where('tutores.id', '=', $tutor->id)
        ->select('personas.*', 'tutores.id AS idTutor', 'tutores.parentesco')
        ->first();

        $alumnos = Persona::join('alumnos', 'alumnos.id_persona', 'personas.id')
        ->where('alumnos.id_tutor', '=', $tutor->id)
        ->get();

        return view('Apoderado.show', compact('persona', 'alumnos'));

    }

    public function create()
    {
        $actionform = route('apoderado.store');
        return view('Apoderado.create', compact('actionform'));
    }

    public function store(StoreApoderado $request)
    {
        $persona = Persona::create([
            'nombre'       => $request->nombre,
            'apellido_pat' => $request->apellido_pat,
            'apellido_mat' => $request->apellido_mat,
            'ci'           => $request->ci,
            'fecha_nac'    => $request->fecha_nac,
            'sexo'         => $request->sexo,
            'email'        => $request->email,
            'direccion'    => $request->direccion,
            'telefono'     => $request->telefono,
        ]);
        $persona->save();

        $apoderado = tutores::create([
            'id_persona' => $persona->id,
            'parentesco' => $request->parentesco,
        ]);
        $apoderado->save();

        bitacoraController::bitacoraRegister(Auth::user()->id, 'Apoderado registrado ID: '.$apoderado->id);

        return redirect()->route('apoderado.index')->with(
            'success',
            'Apoderado creado correctamente'
        );
    }

    public function destroy($id)
    {
        $tutor = tutores::findOrFail($id);
        $tutor->delete();

        bitacoraController::bitacoraRegister(Auth::user()->id, 'Apoderado eliminado ID: '.$tutor->id);

        return redirect()->route('apoderado.index')->with('success', 'Apoderado eliminado correctamente');
    }

    public function edit($id)
    {
        $tutor = tutores::findOrFail($id);
        $persona = Persona::findOrFail($tutor->id_persona);
        $actionform = route('apoderado.update', $tutor);
        return view('Apoderado.edit', compact('tutor', 'persona', 'actionform'));
    }

    public function update($tutorId, StoreApoderado $request)
    {
        $tutor = tutores::findOrfail($tutorId);
        $persona = Persona::findOrfail($tutor->id_persona);

        $persona->nombre = $request->nombre;
        $persona->apellido_pat = $request->apellido_pat;
        $persona->apellido_mat = $request->apellido_mat;
        $persona->ci = $request->ci;
        $persona->fecha_nac = $request->fecha_nac;
        $persona->sexo = $request->sexo;
        $persona->email = $request->email;
        $persona->direccion = $request->direccion;
        $persona->telefono = $request->telefono;

        $persona->save();

        $tutor = tutores::findOrfail($tutorId);
        $tutor->parentesco = $request->parentesco;
        $tutor->save();

        bitacoraController::bitacoraRegister(Auth::user()->id, 'Modificacion de datos del apoderado ID: '.$tutor->id);

        return redirect()->route('apoderado.show', $tutor->id)->with('success', 'Apoderado editado correctamente');
    }
}

resources/views/Apoderado/create.blade.php
@extends('layouts.datosPersonales_plantilla')

@section('title', 'Registro de Apoderados/Tutores')
@section('css')
<style>
    @media(max-width: 850px){
        section div.col-9{
            width: 100%;
        }
    }

    @media(max-width: 600px){
       .card.shadow.m-5{
           margin: 3rem 0 0 0 !important;
       }
    }

</style>
@endsection
@section('subtitle', 'Informacion Adicional')

@section('adicional-information')
<div class="row mb-3 justify-content-around">
    <div class="col m-2">
        <label for="parentesco">
            Parentesco<br>
        </label>
        <input class="form-control" id="parentesco" type="text" name="parentesco" value="{{old('parentesco')}}" form="register_form">
        {!! $errors->first('parentesco', '<span class="help-block text-danger">*:message</span>') !!}
    </div>
</div>
@endsection
@section('btn')
    <a class="btn btn-danger" href="{{route('apoderado.index')}}">Cancelar</a>
@endsection

resources/views/Apoderado/edit.blade.php
@extends('layouts.home_plantilla')
@section('css')
<style>
    @media(max-width: 850px){
        section div.col-9{
            width: 100%;
        }
    }

    @media(max-width: 600px){
       .card.shadow.m-5{
           margin: 3rem 0 0 0 !important;
       }
    }

</style>
    
@endsection
@section('navigation')
<section class="row justify-content-center" id="main">
    <div class="col-9">
        <div class="card shadow mt-1">
            <div class="card-header">
                <h5 class="m-2">Datos Personales a editar</h5>
            </div>
            <div class="card-body p-4">
                <form method="POST" id='register_form' action="{{$actionform}}"> 
                    @csrf
                    @method('PUT')
                    <div class="row mb-3 justify-content-around"> 
                        <div class="col m-2"> 
                            <label for="nombre">
                                Nombre<br>
                            </label>
                            <input class="form-control" id="nombre" type="text" name="nombre" value="{{$persona->nombre}}">
                            {!! $errors->first('nombre', '<span class="help-block text-danger">*:message</span>') !!}
                        </div>
                        <div class="col m-2">
                            <label for="apellidoPat">
                                Apellido paterno<br>
                            </label>
                            <input class="form-control" id="apellidoPat" type="text" name="apellido_pat" value = "{{$persona->apellido_pat}}">
                            {!! $errors->first('apellido_pat', '<span class="help-block text-danger">*:message</span>') !!}
                        </div>
                    </div>
                    <div class="row mb-3 justify-content-around">
                        <div class="col m-2">
                            <label for="apellidoMat">
                                Apellido materno<br>
                            </label>
                            <input class="form-control" id="apellidoMat" type="text" name="apellido_mat" value="{{$persona->apellido_mat}}">
                            {!! $errors->first('apellido_mat', '<span class="help-block text-danger">*:message</span>') !!}
                        </div>
                    </div>
                    <div class="row mb-3 justify-content-around">
                        <div class="col m-2">
                            <label for="ci">
                                Cédula de identidad<br>
                            </label>
                            <input class="form-control" id="ci" type="number" name="ci" value="{{$persona->ci}}">
                        </div>
                        <div class="col m-2">
                            <label for="email">
                                Email<br>
                            </label>
                            <input class="form-control" id="email" type="email" name="email" value= "{{$persona->email}}">
                            {!! $errors->first('email', '<span class="help-block text-danger">*:message</span>') !!}
                        </div>
                    </div>
                    <div class="row mb-3 justify-content-around">
                        <div class="col m-2">
                            <label for="fechaNac">
                                Fecha de nacimiento<br>
                            </label>
                            <input class="form-control" id="fechaNac" type="date" name="fecha_nac" value= "{{$persona->fecha_nac}}">
                            {!! $errors->first('fecha_nac', '<span class="help-block text-danger">*:message</span>') !!}
                        </div>
                        <div class="col m-2">
                            <p class="mb-1">
                                Género
                            </p>
                            <div class="form-check form-check-inline">
                                <input class="form-check-input" id="hombre" type="radio" name="sexo" value="M"
                                @if ($persona->sexo === 'M')
                                    checked
                                @endif
                                >
                                <label for="hombre">Hombre</label>
                            </div>
                            <div class="form-check form-check-inline">
                                <input class="form-check-input" id="mujer" type="radio" name="sexo" value="F"
                                @if ($persona->sexo === 'F')
                                    checked
                                @endif
                                >
                                <label for="mujer">Mujer</label>
                            </div>
                            {!! $errors->first('sexo', '<span class="help-block text-danger">*:message</span>') !!}
                        </div>
                    </div>
                    <div class="row mb-3 justify-content-around">
                        <div class="col m-2">
                            <label>
                                Dirección<br>
                            </label>
                            <input class="form-control" type="text" name="direccion" value="{{$persona->direccion}}">
                            {!! $errors->first('direccion', '<span class="help-block text-danger">*:message</span>') !!}
                        </div>
                        <div class="col m-2">
                            <label>
                                Telefono<br>
                            </label>
                            <input class="form-control" type="tel" name="telefono" value="{{$persona->telefono}}">
                            {!! $errors->first('telefono', '<span class="help-block text-danger">*:message</span>') !!}
                        </div>
                    </div>
                    <section class="row justify-content-center" id="main">
                        <div class="col-12">
                            <div class="card shadow m-5">
                                <div class="card-header">
                                    <h5 class="m-2"> Información adicional</h5>
                                </div>
                                <div class="card-body p-4">
                                    <div class="row mb-3 justify-content-around">
                                        <div class="col m-2">
                                            <label>
                                                Parentesco<br>
                                            </label>
                                            <input class="form-control" type="text" name="parentesco" value="{{$tutor->parentesco}}">
                                            {!! $errors->first('parentesco', '<span class="help-block text-danger">*:message</span>') !!}
                                        </div>
                                    </div>
                                    </div>
                                </div>
                            </div>
                            <div class="mt-3 text-end me-2">

                                <a class="btn btn-danger" href="{{route('apoderado.index')}}">Cancelar</a>

                                <button type="submit" onclick="sendForm()" class="btn btn-primary">
                                    Editar
                                </button>
                            </div>
                        </div>
                        
                    </section>
                    
                </form>
            </div>
        </div>
    </div>
    
    </section>
    </div>
    <script>
        function sendForm() {
            document.all['register_form'].submit();
        }
    </script>
@endsection

resources/views/Apoderado/index.blade.php
@extends('layouts.home_plantilla')

@section('title', 'Apoderados')

@section('navigation')

    <div class="row justify-content-center">
        <div class="col-11  card mt-1">
            <div class="row justify-content-between mb-2 card-header">
                <div class="col">
                    <h2>Lista de Apoderados</h2>
                </div>
                @if (Auth::user()->id_rol == 1 || Auth::user()->id_rol == 2)
                <div class="col d-flex justify-content-end align-items-center text-end">
                    <a class="btn btn-sm btn-success" href="{{ route('apoderado.create') }}"> Registrar nuevo</a>
                </div>
                @endif
            </div>
        <div class="card-body table-responsive">
            <table id ="table_id" class="table table-round-blue ">
                <thead class="table-head">
                    <tr>
                        <th width="5rem">Nro</th>
                        <th>Nombre</th>
                        <th>Apellidos</th>
                        <th width="120px">Acciones</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($personas as $persona)
                        <tr>
                            <td class="text-center">{{ ++$i }}</td>
                            <td>{{ $persona->nombre }}</td>
                            <td>{{ $persona->apellido_pat }} {{ $persona->apellido_mat }}</td>
                            <td>
                                <a class="btn btn-sm btn-primary" href="{{ route('apoderado.show', $persona->idTutor) }}">Ver</a>
                                @if (Auth::user()->id_rol == 1 || Auth::user()->id_rol == 2)
                                <a class="btn btn-sm btn-secondary"
                                    href="{{ route('apoderado.edit', $persona->idTutor) }}">Editar</a>
                                @endif
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
        </div>
    </div>
@endsection

resources/views/Apoderado/show.blade.php
@extends('layouts.showDatos')
@section('title', 'Informacion del Apoderado')

@section('info-adicional-col1')

<p class="mb-1"><b class="fw-bold text-secondary">Parentesco:
</b> {{$persona->parentesco}}</p>
@endsection

@section('info-adicional-col2')
    @if (count($alumnos) > 0)
        @foreach ($alumnos as $alumno)
            <p class="mb-1"><b class="fw-bold text-secondary">En tutela de:
            </b> {{$alumno->nombre.' '.$alumno->apellido_pat.' '.$alumno->apellido_mat}}</p>
        @endforeach
    @endif
@endsection

@section('botones')
<div class="row justify-content-around mt-3">
    @if (Auth::user()->id_rol == 1 || Auth::user()->id_rol == 2)
    <div class="col text-center">
        <a class="btn btn-secondary" href="{{ route('apoderado.edit', $persona->idTutor) }}">Editar</a>
    </div>
    <div class="col text-center">
        <form action="{{ route('apoderado.destroy', $persona->idTutor) }}" method="POST">
            @csrf
            @method('delete')
            <button type="submit" class="btn btn-danger">Eliminar</button>
        </form>
    </div>
    @endif
</div>
@endsection