routes/web.php
<?php

use App\Http\Controllers\administrativoController;
use App\Http\Controllers\alumnoController;
use App\Http\Controllers\bitacoraController;
use App\Http\Controllers\apoderadoController;
use App\Http\Controllers\boletinController;
use App\Http\Controllers\cardexController;
use App\Http\Controllers\cursoController;
use App\Http\Controllers\homeController;
use App\Http\Controllers\inscripcionController;
use App\Http\Controllers\materiaController;
use App\Http\Controllers\notasController;
use App\Http\Controllers\pagoMensualidadController;
use App\Http\Controllers\pagoSalarioController;
use App\Http\Controllers\profesorController;
use App\Http\Controllers\registroController;
use App\Http\Controllers\usuarioController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();

Route::get('welcome', function() {
    return view('welcome');
});


Route::get('/', [\App\Http\Controllers\Auth\LoginController::class, 'showLoginForm']);
Route::get('/home', [HomeController::class, 'homePage'])->name('home')->middleware('auth');

//ruta para el home
Route::resource('home', homeController::class);

//ruta para alumno
Route::resource('alumno', alumnoController::class);

//ruta para apoderado
Route::resource('apoderado', apoderadoController::class);

//ruta para profesor
Route::resource('profesor', profesorController::class);

//ruta para administrativo
Route::resource('administrativo', administrativoController::class);

//ruta para usuario
Route::resource('usuario', usuarioController::class);
Route::post('usuario/{id}/reset', [usuarioController::class, 'updateEstado'])->name('reset');

//ruta para materia
Route::resource('materia', materiaController::class);

//ruta para curso
Route::resource('curso', cursoController::class);

//ruta para la inscripcion
Route::resource('inscripcion', inscripcionController::class);

//rutas para pago mensualidad
Route::resource('mensualidad', pagoMensualidadController::class);
Route::get('mensualidad/index/download-PDF', [pagoMensualidadController::class, 'PDFList'])->name('mensualidad.PDFList');


//ruta para cardex
Route::resource('cardex', cardexController::class);


//ruta para bitacora
Route::resource('bitacora', bitacoraController::class)->only(['show','index']);
Route::get('bitacora/{id}/download-PDF', [bitacoraController::class, 'downloadPDF'])->name('bitacora.pdf');


//ruta para pago salario
Route::resource('salario',pagoSalarioController::class);
Route::get('salario/index/dowload-PDF', [pagoSalarioController::class,'PDFList'])->name('salario.PDFList');

//ruta para boletin
Route::get('/boleta/{id}/trim1',[boletinController::class, 'trim1'])->name('boletin.trim1');
Route::get('/boleta/{id}/trim2',[boletinController::class, 'trim2'])->name('boletin.trim2');
Route::get('/boleta/{id}/trim3',[boletinController::class, 'trim3'])->name('boletin.trim3');
Route::get('/reporteTrim1/{id}','App\Http\Controllers\boletinController@reporteTrim1')->name('boletinTrim1');
Route::get('/reporteTrim2/{id}','App\Http\Controllers\boletinController@reporteTrim2')->name('boletinTrim2');
Route::get('/reporteTrim3/{id}','App\Http\Controllers\boletinController@reporteTrim3')->name('boletinTrim3');
Route::resource('boletin',boletinController::class);

//ruta para reportes
Route::get('/reporteMensualidad/{id}', 'App\Http\Controllers\pagoMensualidadController@generarReporte')->name('reporteMensualidad');
Route::get('/reporteSalario/{id}', 'App\Http\Controllers\pagoSalarioController@generarReporte')->name('reporteSalario');



//ruta para las notas
Route::get('/notasMod', [notasController::class, 'mod'])->name('mod.notas');
Route::resource('notas', notasController::class);

app/Http/Controllers/profesorController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\StoreProfesor;
use App\Models\materias;
use App\Models\Persona;
use App\Models\profesores;
use App\Models\User;
use App\Models\usuario;
use Faker\Provider\ar_JO\Person;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Hash;


class profesorController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
        $this->middleware("roles:Director,Secretaria,none");
    }

    public function index() {
        $personas = Persona::join('profesores', 'personas.id', 'profesores.id_persona')
        ->join('materias', 'profesores.id', 'materias.id_profesor')
        ->orderBy('personas.id', 'asc')
        ->select('personas.*','materias.nombre as nombreMateria', 'profesores.id as idProfesor')->get();
        return view('Profesor.index', compact('personas'))->with('i');
    }

    public function show($profesorId) {
        $profesor = profesores::findOrFail($profesorId);
        
        $persona = Persona::join('profesores', 'profesores.id_persona', 'personas.id')
        ->where('profesores.id', '=', $profesor->id)
        ->select('personas.*', 'profesores.id AS idProfesor', 'profesores.profesion')
        ->first();

        $materia = materias::join('profesores', 'profesores.id', 'materias.id_profesor')
        ->where('profesores.id', '=', $profesor->id)
        ->first();

        return view('Profesor.show', compact('persona', 'materia'));
    }

    public function create(){
        $actionform = route("profesor.store"); 
        return view('Profesor.create', compact('actionform'));
    }

    public function store (StoreProfesor $request){
        $persona = Persona::create([
            'nombre'=> $request->nombre,
            'apellido_pat' => $request->apellido_pat,
            'apellido_mat' => $request-> apellido_mat,
            'ci' => $request->ci,
            'fecha_nac' => $request->fecha_nac,
            'sexo'=> $request->sexo,
            'email'=> $request->email,
            'direccion'=> $request->direccion,
            'telefono'=>$request->telefono ,
        ]);
        $persona->save();

        $usuario = new usuario();
        $usuario->nombre_usuario = $persona->email;
        $usuario->contrasenha = Hash::make($persona->ci);
        $usuario->id_rol = 3;
        $usuario->estado = 1;
        $usuario->save();

        $profesor = new profesores();
        $profesor->id_persona = $persona->id;
        $profesor->profesion = $request->profesion;
        $profesor->id_usuario = $usuario->id;
        $profesor->save();

        bitacoraController::bitacoraRegister(Auth::user()->id, 'Profesor registrado ID: '.$profesor->id);
      
       return redirect()->route('profesor.index')->with(
        'success',
        'Profesor creado correctamente'
    );
    }


    public function edit($id){
        $profesor = profesores::findOrFail($id);
        $persona = Persona::findOrFail($profesor->id_persona);
        $actionform = route('profesor.update',[$profesor->id]); 
       return view('Profesor.edit', compact('profesor','persona','actionform'));
      
    }

    public function update($id, StoreProfesor $request){

        $profesor = profesores::findOrFail($id);
        $profesor->profesion = $request->profesion;
        $profesor->save();

        $persona = Persona::findOrfail($profesor->id_persona);

        $persona->nombre= $request->nombre;
        $persona->apellido_pat = $request->apellido_pat;
        $persona->apellido_mat = $request-> apellido_mat;
        $persona->ci = $request->ci;
        $persona->fecha_nac = $request->fecha_nac;
        $persona->sexo= $request->sexo;
        $persona->email= $request->email;
        $persona->direccion= $request->direccion;
        $persona->telefono=$request->telefono; 

        $persona->save();

        bitacoraController::bitacoraRegister(Auth::user()->id, 'Modificacion de datos Profesor ID: '.$profesor->id);

        return view('Profesor.show', compact('persona', 'profesor'));
    }

    public function destroy($id){
        $persona = Persona::findOrFail($id);
        $persona->delete();

        bitacoraController::bitacoraRegister(Auth::user()->id, 'Profesor eliminado ID Persona: '.$persona->id);

        return redirect()->route('Profesor.index')->with('success', 'Profesor eliminado correctamente');
    }
}

resources/views/Profesor/create.blade.php
@extends('layouts.datosPersonales_plantilla')

@section('title', 'Registro de Profesor')
@section('css')
<style>
    @media(max-width: 850px){
        section div.col-9{
            width: 100%;
        }
    }

    @media(max-width: 600px){
       .card.shadow.m-5{
           margin: 3rem 0 0 0 !important;
       }
    }

</style>
@endsection
@section('form-action', '')

@section('subtitle', 'Información Adicional')

@section('adicional-information')
        <div class="col m-2">
            <label for="profesion">
                Profesión<br>
            </label>
            <input form="register_form" class="form-control" 
            id="profesion" type="text" name="profesion" value="{{old('nombre')}}">
            {!! $errors->first('profesion', '<span class="help-block text-danger">*:message</span>') !!}
        </div>
@endsection
@section('btn')
    <a class="btn btn-danger" href="{{route('profesor.index')}}">Cancelar</a>
@endsection

resources/views/Profesor/edit.blade.php
@extends('layouts.home_plantilla')
@section('css')
<style>
    @media(max-width: 850px){
        section div.col-9{
            width: 100%;
        }
    }

    @media(max-width: 600px){
       .card.shadow.m-5{
           margin: 3rem 0 0 0 !important;
       }
    }

</style>
    
@endsection
@section('navigation')
<section class="row justify-content-center" id="main">
    <div class="col-9">
        <div class="card shadow mt-1">
            <div class="card-header">
                <h5 class="m-2">Datos Personales a editar</h5>
            </div>
            <div class="card-body p-4">
                <form method="POST" id='register_form' action="{{$actionform}}"> 
                    @csrf
                    @method('PUT')
                    <div class="row mb-3 justify-content-around"> 
                        <div class="col m-2"> 
                            <label for="nombre">
                                Nombre<br>
                            </label>
                            <input class="form-control" id="nombre" type="text" name="nombre" value="{{$persona->nombre}}")>
                            {!! $errors->first('nombre', '<span class="help-block text-danger">*:message</span>') !!}
                        </div>
                        <div class="col m-2">
                            <label for="apellidoPat">
                                Apellido paterno<br>
                            </label>
                            <input class="form-control" id="apellidoPat" type="text" name="apellido_pat" value = "{{$persona->apellido_pat}}">
                            {!! $errors->first('apellido_pat', '<span class="help-block text-danger">*:message</span>') !!}
                        </div>
                    </div>
                    <div class="row mb-3 justify-content-around">
                        <div class="col m-2">
                            <label for="apellidoMat">
                                Apellido materno<br>
                            </label>
                            <input class="form-control" id="apellidoMat" type="text" name="apellido_mat" value="{{$persona->apellido_mat}}">
                            {!! $errors->first('apellido_mat', '<span class="help-block text-danger">*:message</span>') !!}
                        </div>
                    </div>
                    <div class="row mb-3 justify-content-around">
                        <div class="col m-2">
                            <label for="ci">
                                Cédula de identidad<br>
                            </label>
                            <input class="form-control" id="ci" type="number" name="ci" value="{{$persona->ci}}">
                            {!! $errors->first('ci', '<span class="help-block text-danger">*:message</span>') !!}
                        </div>
                        <div class="col m-2">
                            <label for="email">
                                Email<br>
                            </label>
                            <input class="form-control" id="email" type="email" name="email" value= "{{$persona->email}}">
                            {!! $errors->first('email', '<span class="help-block text-danger">*:message</span>') !!}
                        </div>
                    </div>
                    <div class="row mb-3 justify-content-around">
                        <div class="col m-2">
                            <label for="fechaNac">
                                Fecha de nacimiento<br>
                            </label>
                            <input class="form-control" id="fechaNac" type="date" name="fecha_nac" value= "{{$persona->fecha_nac}}">
                            {!! $errors->first('fecha_nac', '<span class="help-block text-danger">*:message</span>') !!}
                        </div>
                        <div class="col m-2">
                            <p class="mb-1">
                                Género
                            </p>
                            <div class="form-check form-check-inline">
                                <input class="form-check-input" id="hombre" type="radio" name="sexo" value="M"
                                @if ($persona->sexo === 'M')
                                    checked
                                @endif
                                >
                                <label for="hombre">Hombre</label>
                            </div>
                            <div class="form-check form-check-inline">
                                <input class="form-check-input" id="mujer" type="radio" name="sexo" value="F"
                                @if ($persona->sexo === 'F')
                                    checked
                                @endif
                                >
                                <label for="mujer">Mujer</label>
                            </div>
                            {!! $errors->first('sexo', '<span class="help-block text-danger">*:message</span>') !!}
                        </div>
                    </div>
                    <div class="row mb-3 justify-content-around">
                        <div class="col m-2">
                            <label>
                                Dirección<br>
                            </label>
                            <input class="form-control" type="text" name="direccion" value="{{$persona->direccion}}">
                            {!! $errors->first('direccion', '<span class="help-block text-danger">*:message</span>') !!}
                        </div>
                        <div class="col m-2">
                            <label>
                                Telefono<br>
                            </label>
                            <input class="form-control" type="tel" name="telefono" value="{{$persona->telefono}}">
                            {!! $errors->first('telefono', '<span class="help-block text-danger">*:message</span>') !!}
                        </div>
                    </div>
                    <section class="row justify-content-center" id="main">
                        <div class="col-12">
                            <div class="card shadow m-5">
                                <div class="card-header">
                                    <h5 class="m-2"> Información adicional</h5>
                                </div>
                                <div class="card-body p-4">
                                    <div class="row mb-3 justify-content-around">
                                        <div class="col m-2">
                                            <label for="profesion">
                                                Profesión<br>
                                            </label>
                                            <input form="register_form" class="form-control" 
                                            id="profesion" type="text" name="profesion" value="{{$profesor->profesion}}">
                                            {!! $errors->first('profesion', '<span class="help-block text-danger">*:message</span>') !!}
                                        </div>
                                    </div>
                                    </div>
                                </div>
                                
                            </div>
                            <div class="mt-3 text-center me-2">
                                <button type="submit" onclick="sendForm()" class="btn btn-primary">
                                    Editar
                                </button>
                            </div>
                        </div>
                        
                    </section>
                    
                </form>
            </div>
        </div>
    </div>
    
    </section>
    </div>
    <script>
        function sendForm() {
            document.all['register_form'].submit();
        }
    </script>
@endsection

resources/views/Profesor/index.blade.php
@extends('layouts.home_plantilla')

@section('title', 'Profesor')

@section('navigation')

    <div class="row justify-content-center">
        <div class="col-11 mt-1 card" >
            <div class="row justify-content-between mb-2 card-header">
                <div class="col">
                    <h2>Lista de Profesores</h2>
                </div>
                <div class="col d-flex justify-content-end align-items-center">
                    <a class="btn btn-sm btn-success" href="{{ route('profesor.create') }}"> Registrar nuevo</a>
                </div>
            </div>
           <div class="card-body table-responsive">
                <table class="table table-round-blue table-sm table-striped">
                    <thead class="table-head">
                        <tr>
                            <th width = "5rem" >Nro</th>
                            <th>Nombre</th>
                            <th>Apellidos</th>
                            <th>Materia</th>
                            <th width="120px">Acciones</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($personas as $persona)
                            <tr>
                                <td class="text-center">{{ ++$i }}</td>
                                <td>{{ $persona->nombre }}</td>
                                <td>{{ $persona->apellido_pat }} {{ $persona->apellido_mat }}</td>
                                <td>{{ $persona->nombreMateria}}</td>
                                <td>
                                    <a class="btn btn-sm btn-primary" href="{{ route('profesor.show', $persona->idProfesor) }}">Ver</a>
                                    <a class="btn btn-sm btn-secondary" href="{{ route('profesor.edit', $persona->idProfesor) }}">Editar</a>
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
           </div>
         
        </div>
    </div>
@endsection

resources/views/Profesor/show.blade.php
@extends('layouts.showDatos')
@section('title', 'Informacion del Apoderado')

@section('info-adicional-col1')

<p class="mb-1"><b class="fw-bold text-secondary">Profesión:
</b> {{$persona->profesion}}</p>
@endsection

@section('info-adicional-col2')
<p class="mb-1"><b class="fw-bold text-secondary">Materia:
</b> {{$materia->nombre}}</p>
@endsection

@section('botones')
<div class="row justify-content-around mt-3">
    @if (Auth::user()->id_rol == 1 || Auth::user()->id_rol == 2)
    <div class="col text-center">
        <a class="btn btn-secondary" href="{{ route('profesor.edit', $persona->idProfesor) }}">Editar</a>
    </div>
    <div class="col text-center">
        <form action="{{ route('profesor.destroy', $persona->idProfesor) }}" method="POST">
            @csrf
            @method('delete')
            <button type="submit" class="btn btn-danger">Eliminar</button>
        </form>
    </div>
    @endif
</div>
@endsection